[package]
name = "async-jsonrpc-client"
version = "0.1.2"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"
description = "An asynchronous JSON-RPC client library, which supports HTTP and WebSocket"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/koushiro/async-jsonrpc-client-rs"
keywords = ["async", "jsonrpc", "client"]

[features]
default = ["http", "ws"]
http = ["reqwest"]
ws = ["async-tungstenite", "parking_lot", "tokio"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

# HTTP
reqwest = { version = "0.10", features = ["json"], optional = true }

# WebSocket
async-tungstenite = { version = "0.7", features = ["tokio-runtime"], optional = true }
parking_lot = { version = "0.11", optional = true }
tokio = { version = "0.2", features = ["macros"], optional = true }

[dev-dependencies]
env_logger = "0.7"
