[package]
name = "jsonrpc-client"
version = "0.1.0"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"
description = "A JSON-RPC client library"

[features]
default = ["http", "ws"]
http = ["reqwest"]
ws = ["async-tungstenite", "tokio"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
log = "0.4"
parking_lot = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

# Http
reqwest = { version = "0.10", features = ["json"], optional = true }
# WebSocket
async-tungstenite = { version = "0.4", features = ["tokio-runtime"], optional = true }
tokio = { version = "0.2", features = ["macros"], optional = true }

[dev-dependencies]
env_logger = "0.7"
